# Generated by Django 4.1.7 on 2023-05-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
