import { IMasterClass } from "src/app/models/models";

export const masterClasses: IMasterClass[] = [
    {
      id: 1,
      name: 'Cooking with Chef John',
      date: '2023-05-01T18:00:00Z',
      duration: 120,
      location: '123 Main St, Anytown, USA',
      description: 'Join Chef John for an evening of cooking and culinary exploration!',
      image: 'https://i.pinimg.com/originals/6a/f3/ee/6af3ee218564914163351effeeb3ceb4.jpg',
      price: 75.00,
      maxAttendees: 20,
      attendees: ['Testing', 'Alice', 'Bob', 'Charlie'],
    },
    {
      id: 2,
      name: 'Wine Tasting 101',
      date: '2023-05-15T19:00:00Z',
      duration: 90,
      location: '456 Oak Ave, Anycity, USA',
      description: 'Learn about different types of wine and how to properly taste and evaluate them.',
      image: 'https://i.pinimg.com/originals/64/aa/d9/64aad9fe7a3fc4df8900e67dc7a55509.jpg',
      price: 50.00,
      maxAttendees: 15,
      attendees: ['Something', 'Bobik', 'Frank', 'Grace'],
    },
    {
      id: 3,
      name: 'Photography Workshop',
      date: '2023-06-01T09:00:00Z',
      duration: 240,
      location: '789 Elm St, Anyville, USA',
      description: 'Improve your photography skills with expert guidance and hands-on practice.',
      image: 'https://phuquoc.intercontinental.com/uploads/phuquoc/Blog/ThaiChef/thai%20chef_rz2.jpg',
      price: 150.00,
      maxAttendees: 10,
      attendees: ['John', 'Henry', 'Isabel', 'Jack', 'Kate'],
    },
];
