# Generated by Django 4.1.7 on 2023-05-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_ingredients_remove_recipe_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
