# Generated by Django 4.1.7 on 2023-05-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_category_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
