# Generated by Django 4.1.7 on 2023-05-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_category_recipe_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category_id',
        ),
    ]
