# Generated by Django 5.0.4 on 2024-04-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='showtimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('participants', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
